In [4]:
import requests
import json
import pandas as pd

response = requests.get("https://ubcgrades.com/api/v3/grades/UBCV/2022S")
data = response.json()
df = pd.json_normalize(data)
df

,average,campus,course,course_title,detail,educators,faculty_title,high,low,median,...,grades.55-59%,grades.60-63%,grades.64-67%,grades.68-71%,grades.72-75%,grades.76-79%,grades.80-84%,grades.85-89%,grades.90-100%,grades.<50%
0,89.000000,UBCV,390,Asian Migrations in a Global Context,A,Henry Yu,Faculty of Arts,92,85,89.0,...,0,0,0,0,0,0,0,3,3,0
1,89.000000,UBCV,390,Asian Migrations in a Global Context,A,None,Faculty of Arts,92,85,NaN,...,0,0,0,0,0,0,0,3,3,0
2,81.700000,UBCV,327,Teaching Adults,,Sharon Jarvis,Faculty of Education,94,59,81.0,...,1,0,1,1,0,6,7,5,5,0
3,78.200000,UBCV,327,Teaching Adults,,Sharon Jarvis,Faculty of Education,91,0,83.0,...,0,0,1,2,0,4,9,7,1,1
4,82.500000,UBCV,327,Teaching Adults,,Vicheth Sen,Faculty of Education,90,70,83.0,...,0,0,0,1,2,3,11,10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1718,75.500000,UBCV,150,Writing and Research in the Disciplines,B,Connor Byrne,Faculty of Arts,88,31,78.0,...,0,1,0,1,6,9,5,5,0,1
1719,79.400000,UBCV,150,Writing and Research in the Disciplines,B,David Newman,Faculty of Arts,85,74,78.0,...,0,0,0,0,1,13,6,4,0,0
1720,78.400000,UBCV,150,Writing and Research in the Disciplines,B,Sang Yin Wu,Faculty of Arts,90,57,80.0,...,1,0,1,1,3,4,7,4,1,0
1721,74.400000,UBCV,150,Writing and Research in the Disciplines,B,Rohan Karpe,Faculty of Arts,83,48,75.5,...,0,1,1,3,8,8,6,0,0,1
1722,76.245719,UBCV,150,Writing and Research in the Disciplines,B,None,Faculty of Arts,99,0,NaN,...,16,27,32,53,68,131,165,93,44,17

# Import grades into dataframe
API: https://ubcgrades.com/api/v3/grades/UBCV/2022S
Options: `/grades/campus/yearsession` 
- campus: `UBCV` or `UBCO`
Note: '[V3] carries data from 2019W onward...Some endpoints are not available in v3, and v2 should be used instead.'

NOTE: this opens up a webapplication on localhost. For me, it is port 8050 (localhost:8050)

In [5]:
from dash import Dash, html, dcc, callback, Output, Input
import plotly.express as px
# import pandas as pd

# df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder_unfiltered.csv')

app = Dash(__name__)

app.layout = html.Div([
    html.H1(children='Title of Dash App', style={'textAlign':'center'}),
    dcc.Dropdown(df.faculty_title.unique(), 'Faculty of Arts', id='dropdown-selection'),
    dcc.Dropdown(df.subject.unique(), "CPSC", id="xaxis-column"),
    dcc.Dropdown(df.course.unique(), "210", id="yaxis-column"),
    dcc.Graph(id='graph-content')
    dcc.Slider(
            df.year.min(),
            df.year.max(),
            step=None,
            id="year--slider",
            value=df.year.max(),
            marks={str(year): str(year) for year in df.year.unique()},
        ),
])

@callback(
    Output('graph-content', 'figure'),
    Input('dropdown-selection', 'value')
    Input("year--slider", "value"),
)
def update_graph(value):
    dff = df[df.faculty_title==value]
    return px.line(dff, x='course', y='average')

if __name__ == '__main__':
    app.run(debug=True)

SyntaxError: invalid syntax (2246357531.py, line 15)

: